SET time_zone = '+08:00';
DROP DATABASE IF EXISTS WORKSHOP;
CREATE DATABASE IF NOT EXISTS WORKSHOP CHARACTER SET utf8mb4;
USE WORKSHOP;

DROP TABLE IF EXISTS MOVIE;
CREATE TABLE MOVIE
(
	MOVIE_ID INTEGER AUTO_INCREMENT, 
	MOVIE_TITLE VARCHAR(50) NOT NULL,
	MOVIE_GENRES VARCHAR(200) NOT NULL,
	MOVIE_DURATION INTEGER(3) NOT NULL,
	MOVIE_RELEASE_DATE DATE NOT NULL,
	MOVIE_SYNOPSIS TEXT NOT NULL,
	MOVIE_ACTOR VARCHAR(200) NOT NULL,
    MOVIE_DISTRIBUTOR VARCHAR(50) NOT NULL,
	MOVIE_ORIGINAL_LANGUAGE CHAR(30) NOT NULL,
	
	PRIMARY KEY (MOVIE_ID)
);

CREATE TABLE CINEMA
(
	CINEMA_ID INTEGER(3),
	CINEMA_NAME VARCHAR(50) NOT NULL UNIQUE,
	CINEMA_ADDRESS VARCHAR(200) NOT NULL UNIQUE,
	
	PRIMARY KEY (CINEMA_ID)
);

CREATE TABLE ACCOUNT
(
	ACCOUNT_ID INTEGER(5) AUTO_INCREMENT,
	USERNAME VARCHAR(50) NOT NULL,
	PHONE VARCHAR(15) NOT NULL UNIQUE,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	PASSWORD VARCHAR(50) NOT NULL,
    ROLE INTEGER(1) NOT NULL, 
	CINEMA_ID INTEGER(3),
	
	PRIMARY KEY (ACCOUNT_ID),
	FOREIGN KEY (CINEMA_ID) REFERENCES CINEMA (CINEMA_ID)
);

CREATE TABLE HALL
(
	HALL_ID INTEGER(4),
	HALL_NUM TINYINT(2) NOT NULL,
	NUM_ROW TINYINT(2) NOT NULL,
    NUM_SEAT_PER_ROW TINYINT(2) NOT NULL,
	HALL_TYPE TINYINT(2) NOT NULL,
	CINEMA_ID INTEGER(3) NOT NULL,
	
	PRIMARY KEY (HALL_ID),
	FOREIGN KEY (CINEMA_ID) REFERENCES CINEMA (CINEMA_ID)
);

CREATE TABLE HALL_TYPE
(
	HALL_TYPE_ID TINYINT(2) AUTO_INCREMENT,
	HALL_TYPE TINYINT(1) NOT NULL,
	HALL_NAME VARCHAR(20) NOT NULL,
	DEFAULT_PRICE DECIMAL(4,2) NOT NULL,
	UPDATE_TIME TIMESTAMP NOT NULL,
	
	PRIMARY KEY (HALL_TYPE_ID)
);

CREATE TABLE HALL_SEAT
(
	SEAT_ID INTEGER(5) AUTO_INCREMENT,
	SEAT_ROW TINYINT(2) NOT NULL,
	SEAT_NO TINYINT(2) NOT NULL,
    HALL_ID INTEGER(4) NOT NULL,
	
	PRIMARY KEY (SEAT_ID),
	FOREIGN KEY (HALL_ID) REFERENCES HALL (HALL_ID)
);

CREATE TABLE MOVIE_SHOWTIME
(
	MOVIE_SHOW_ID INTEGER AUTO_INCREMENT,
	MOVIE_ID INTEGER NOT NULL,
	HALL_ID INTEGER(4) NOT NULL,
	SHOW_DATE DATE NOT NULL,
	SHOW_TIME TIME NOT NULL,
	DURATION INTEGER NOT NULL,
	
	PRIMARY KEY (MOVIE_SHOW_ID),
	FOREIGN KEY (MOVIE_ID) REFERENCES MOVIE (MOVIE_ID),
	FOREIGN KEY (HALL_ID) REFERENCES HALL (HALL_ID)
);

CREATE TABLE BOOKING 
(
	BOOKING_ID INTEGER,
	MOVIE_SHOW_ID INTEGER NOT NULL,
	BOOKING_DATE_TIME DATETIME NOT NULL,
    TOTAL_PRICE DECIMAL(4,2) NOT NULL,
	BUYER_ID INTEGER(5),
    
	PRIMARY KEY (BOOKING_ID),
	FOREIGN KEY (BUYER_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
	FOREIGN KEY (MOVIE_SHOW_ID) REFERENCES MOVIE_SHOWTIME (MOVIE_SHOW_ID)
);

CREATE TABLE TICKET
(
	TICKET_ID INTEGER AUTO_INCREMENT,
	SEAT_ID INTEGER(5) NOT NULL,
	BOOKING_ID INTEGER NOT NULL,
	
	PRIMARY KEY (TICKET_ID),
	FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING (BOOKING_ID),
	FOREIGN KEY (SEAT_ID) REFERENCES HALL_SEAT (SEAT_ID)
	
);

COMMIT;